### ISSUE TITLE
"go->loot.AddItem(storeItem) " is not working

### ISSUE THREAD

**Issue by Veraciel** [talamortis/mod-PvPScript#3]
for (int i = EQUIPMENT_SLOT_START; i < EQUIPMENT_SLOT_END; ++i)
                    if (Item * pItem = killed->GetItemByPos(INVENTORY_SLOT_BAG_0, i))
                    {
                        uint8 slot = pItem->GetSlot();
                        LootStoreItem storeItem = LootStoreItem(pItem->GetEntry(), 0, 100, 0, LOOT_MODE_DEFAULT, 0, 1, 1);
                        go->loot.AddItem(storeItem);
                        killed->DestroyItem(INVENTORY_SLOT_BAG_0, slot, true);
                    }

I tried to use your awesome script but I have a problem that doesn't really work in my case

The chest is summoned but there is no item from the victim. It's just empty .

How can I fix this?

**Comment by talamortis** [comment]
Script works fine, you need to create a new game object like chest and remove the loot assigned to it. You can do this in gameobject_template table

**Comment by talamortis** [comment]
Change data1 to '0' once that is done assign the right chest to the config script and all should work fine, please be mindful the chest will not drop if players are attacking from the same IP address

**Comment by Veraciel** [comment]
Oh!! Thank you so much! I checked it and the problem was I put the loot template assigned to the data1 that was the problem! Your idea of this script is very awesome. I was making exactly similar one with Eluna Script but you are much more better than my noob skills.

**Comment by talamortis** [comment]
Please let me know if it works for you, if so i can then close this issue :)

**Comment by Veraciel** [comment]
It's perfectly working with your advice. Thank you!
