### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Clawlancer** [talamortis/mod-PvPScript#4]
Hello!

I've tried to use this interesting module in my fresh AzerothCore, but everything builds correctly only this script wont go trough.

">D:\azerothcore-wotlk-master (1)\azerothcore-wotlk-master\modules\PvPScript\src\PvPScript.cpp(91): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'LootStoreItem'
12>D:\azerothcore-wotlk-master (1)\azerothcore-wotlk-master\modules\PvPScript\src\PvPScript.cpp(91): note: No constructor could take the source type, or constructor overload resolution was ambiguous
12>D:\azerothcore-wotlk-master (1)\azerothcore-wotlk-master\modules\PvPScript\src\PvPScript.cpp(91): error C2512: 'LootStoreItem': no appropriate default constructor available
12>D:\azerothcore-wotlk-master (1)\azerothcore-wotlk-master\src\server\game\Loot\LootMgr.h(115): note: see declaration of 'LootStoreItem' (compiling source file D:\azerothcore-wotlk-master (1)\azerothcore-wotlk-master\modules\PvPScript\src\PvPScript.cpp)
12>D:\azerothcore-wotlk-master (1)\azerothcore-wotlk-master\modules\PvPScript\src\PvPScript.cpp(158): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'LootStoreItem'
12>D:\azerothcore-wotlk-master (1)\azerothcore-wotlk-master\modules\PvPScript\src\PvPScript.cpp(158): note: No constructor could take the source type, or constructor overload resolution was ambiguous
12>D:\azerothcore-wotlk-master (1)\azerothcore-wotlk-master\modules\PvPScript\src\PvPScript.cpp(158): error C2512: 'LootStoreItem': no appropriate default constructor available
12>D:\azerothcore-wotlk-master (1)\azerothcore-wotlk-master\src\server\game\Loot\LootMgr.h(115): note: see declaration of 'LootStoreItem' (compiling source file D:\azerothcore-wotlk-master (1)\azerothcore-wotlk-master\modules\PvPScript\src\PvPScript.cpp)
"

Any ideas what am i doing wrong?

Thanks!

**Comment by Clawlancer** [comment]
i was stupid, azerothcore repo had an older version so that was the issue, sorry :D

**Comment by talamortis** [comment]
Haha no problem, glad your getting use of this script :)
