### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Pholoween** [talamortis/mod-PvPScript#5]
Hello, when i rebuild with CMake, i have this message at the end :

`/home/wowserver/R1/_Source/AzerothCore_03-2021/modules/mod-PvPScript-master/src/PvPScript.cpp:53:31: warning: comparison of integers of different signs: 'int' and 'std::vector::size_type' (aka 'unsigned long') [-Wsign-compare]
            for (int i = 0; i < AreatoIgnore.size(); ++i)
                            ~ ^ ~~~~~~~~~~~~~~~~~~~
/home/wowserver/R1/_Source/AzerothCore_03-2021/modules/mod-PvPScript-master/src/PvPScript.cpp:122:31: warning: comparison of integers of different signs: 'int' and 'std::vector::size_type' (aka 'unsigned long') [-Wsign-compare]
            for (int i = 0; i < AreatoIgnore.size(); ++i)
                            ~ ^ ~~~~~~~~~~~~~~~~~~~
/home/wowserver/R1/_Source/AzerothCore_03-2021/modules/mod-PvPScript-master/src/PvPScript.cpp:183:25: fatal error: no member named 'LoadMore' in 'ConfigMgr'
            sConfigMgr->LoadMore(cfg_def_file.c_str());
            ~~~~~~~~~~  ^
2 warnings and 1 error generated.
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/build.make:7853: src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-PvPScript-master/src/PvPScript.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1569: src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
make: *** [Makefile:149: all] Error 2`

But i don't know why

**Comment by talamortis** [comment]
How did you re-produce this issue?

Oh its for Azerothcore.... Not interested.

No longer work on this as they banned me on main repo.

Sorry.

**Comment by pangolp** [comment]
> Hello, when i rebuild with CMake, i have this message at the end :
> 
> `/home/wowserver/R1/_Source/AzerothCore_03-2021/modules/mod-PvPScript-master/src/PvPScript.cpp:53:31: warning: comparison of integers of different signs: 'int' and 'std::vector::size_type' (aka 'unsigned long') [-Wsign-compare] for (int i = 0; i < AreatoIgnore.size(); ++i) ~ ^ ~~~~~~~~~~~~~~~~~~~ /home/wowserver/R1/_Source/AzerothCore_03-2021/modules/mod-PvPScript-master/src/PvPScript.cpp:122:31: warning: comparison of integers of different signs: 'int' and 'std::vector::size_type' (aka 'unsigned long') [-Wsign-compare] for (int i = 0; i < AreatoIgnore.size(); ++i) ~ ^ ~~~~~~~~~~~~~~~~~~~ /home/wowserver/R1/_Source/AzerothCore_03-2021/modules/mod-PvPScript-master/src/PvPScript.cpp:183:25: fatal error: no member named 'LoadMore' in 'ConfigMgr' sConfigMgr->LoadMore(cfg_def_file.c_str()); ~~~~~~~~~~ ^ 2 warnings and 1 error generated. make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/build.make:7853: src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-PvPScript-master/src/PvPScript.cpp.o] Error 1 make[2]: *** Waiting for unfinished jobs.... make[1]: *** [CMakeFiles/Makefile2:1569: src/server/scripts/CMakeFiles/scripts.dir/all] Error 2 make: *** [Makefile:149: all] Error 2`
> 
> But i don't know why

Here you have an update of the module: https://github.com/azerothcore/mod-pvpscript. The community is trying to update the module whenever possible. If you have a report, you can do it within the repository.

**Comment by talamortis** [comment]
Fixed compile https://github.com/talamortis/mod-PvPScript/commit/0cf474d011dac3b6e4bc7d841d9a21663ab46707

**Comment by talamortis** [comment]
> > Hello, when i rebuild with CMake, i have this message at the end :
> > `/home/wowserver/R1/_Source/AzerothCore_03-2021/modules/mod-PvPScript-master/src/PvPScript.cpp:53:31: warning: comparison of integers of different signs: 'int' and 'std::vector::size_type' (aka 'unsigned long') [-Wsign-compare] for (int i = 0; i < AreatoIgnore.size(); ++i) ~ ^ ~~~~~~~~~~~~~~~~~~~ /home/wowserver/R1/_Source/AzerothCore_03-2021/modules/mod-PvPScript-master/src/PvPScript.cpp:122:31: warning: comparison of integers of different signs: 'int' and 'std::vector::size_type' (aka 'unsigned long') [-Wsign-compare] for (int i = 0; i < AreatoIgnore.size(); ++i) ~ ^ ~~~~~~~~~~~~~~~~~~~ /home/wowserver/R1/_Source/AzerothCore_03-2021/modules/mod-PvPScript-master/src/PvPScript.cpp:183:25: fatal error: no member named 'LoadMore' in 'ConfigMgr' sConfigMgr->LoadMore(cfg_def_file.c_str()); ~~~~~~~~~~ ^ 2 warnings and 1 error generated. make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/build.make:7853: src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-PvPScript-master/src/PvPScript.cpp.o] Error 1 make[2]: *** Waiting for unfinished jobs.... make[1]: *** [CMakeFiles/Makefile2:1569: src/server/scripts/CMakeFiles/scripts.dir/all] Error 2 make: *** [Makefile:149: all] Error 2`
> > But i don't know why
> 
> Here you have an update of the module: https://github.com/azerothcore/mod-pvpscript. The community is trying to update the module whenever possible. If you have a report, you can do it within the repository.

i have been banned from the azerothcore repo, therefore i cant push my changes to that.
